on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-push.yml"

jobs:
  check-env:
    permissions:
      contents: none
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      check-docker: ${{ steps.check-docker.outputs.defined }}
    steps:
      - id: check-docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        run: echo "defined=true" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs: check-env
    if: needs.check-env.outputs.check-docker == 'true'
    timeout-minutes: 120
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Get tag to build
        id: tag
        run: |
          # get the tag from Dockerfile
          repo="transmission/transmission"
          tag=$(grep -oP 'ARG TAG=\K[^ ]+' Dockerfile)
          # url=$(curl -sSL --retry 5 "https://api.github.com/repos/$repo/releases" | jq -r ".[] | select(.tag_name == \"$tag\") | .url")

          echo "tag=${tag}" >> $GITHUB_OUTPUT
          # echo "url=${url}" >> $GITHUB_OUTPUT
          echo "pkg=transmission" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag.outputs.pkg }}
            ghcr.io/${{ github.actor }}/${{ steps.tag.outputs.pkg }}
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ steps.tag.outputs.tag }},enable=true
          flavor: latest=auto

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,mode=max,scope=docker-release
          build-args: |
            TAG=${{ steps.tag.outputs.tag }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=$(git rev-parse --short HEAD)
